### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by hunterInt** [MetaMask/eth-sig-util#250]
On page load I'm getting the error `Buffer is not defined`:

![image](https://user-images.githubusercontent.com/14793417/168310463-32c9e9df-bcfd-462c-963e-3749d5de5fa6.png)

It seems to only happen when I've imported the ` '@metamask/eth-sig-util'` script and try to encrypt data:

```
import ethUtil from 'ethereumjs-util'
import sigUtil from '@metamask/eth-sig-util'

const encryptedData = ethUtil.bufferToHex(
  Buffer.from(
    JSON.stringify(
      sigUtil.encrypt({
        publicKey: publicKey,
        data: 'hello world data',
        version: 'x25519-xsalsa20-poly1305',
      })
    ),
    'utf8'
  )
)
```

I've tried adding in `import { Buffer } from 'buffer/'`, but this doesn't seem to help. 
Chrome version: `Version 100.0.4896.88 (Official Build) (64-bit)` on Ubuntu 20 and in FireFox `100.0 (64-bit)`.

If I omit  `import sigUtil from '@metamask/eth-sig-util'` or 
```
const encryptedData = ethUtil.bufferToHex(
  Buffer.from(
    JSON.stringify(
      sigUtil.encrypt({
        publicKey: publicKey,
        data: 'hello world data',
        version: 'x25519-xsalsa20-poly1305',
      })
    ),
    'utf8'
  )
)
```
The error goes away.

**Comment by mcmire** [comment]
Hi @hunterInt. How are you preprocessing your JavaScript? Buffer is a class in the Node standard library, so it works in a Node context, but in a browser context, you will probably need to configure your preprocessor to replace this with a polyfill. If you're using Webpack, then you can:

1. Install the [`buffer`](https://www.npmjs.com/package/buffer) module.
2. Configure Webpack to use it via the [`resolve.fallback` option](https://webpack.js.org/configuration/resolve/#resolvefallback). This should allow you to use Buffer in your own code.
3. Configure Webpack with [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/#root). This should fix dependencies like `ethereumjs-util` so that anywhere Buffer appears, it is automatically replaced with the class exported by `buffer`.

Hope that helps. Let me know if you encounter any more issues.

**Comment by hunterInt** [comment]
Hi @mcmire, thank you so much for explaining that! I'm actually using Vite, but your answer led me to find this answer https://github.com/vitejs/vite/discussions/2785 which solved my problem

**Comment by mcmire** [comment]
Ah, perfect, that makes sense too! Glad I could help. :)

**Comment by SyedImam1998** [comment]
Hey @hunterInt  i am still facing this issue even after adding
`import { Buffer } from 'buffer'`
`globalThis.Buffer = Buffer`
in index.js of react app. Could you please guide me here.

![image](https://user-images.githubusercontent.com/52135949/174784779-9939f953-5137-4e6c-8b87-98a6e641e12d.png)

**Comment by mcmire** [comment]
Hi @SyedImam1998. Did you see my instructions above?
