### ISSUE TITLE
Typings don't compile

### ISSUE THREAD

**Issue by mrwillis** [MetaMask/eth-sig-util#59]
There are two issues

```
node_modules/eth-sig-util/index.d.ts:16:5 - error TS2411: Property 'EIP712Domain' of type 'ITypedField[] | undefined' is not assignable to string index type 'ITypedField[]'.

16     EIP712Domain?: Array<ITypedField>
       ~~~~~~~~~~~~
```

I don't recall `EIP712Domain` being optional in the Types in the spec.

Also 

```typescript
export interface ITypedValue {
  [key: string]: string | number | ITypedValue | ITypedValue[]
}
```

should also allow for `string[]` and `number[]`

**Comment by alcuadrado** [comment]
I'm experiencing the same issue. I believe it's impossible to distribute a TS package that has this one as a dependency.

**Comment by mrwillis** [comment]
Yes it is impossible.

**Comment by danfinlay** [comment]
Sorry this has not been a high priority for me at the moment, I'll get to it when I can, or someone else can submit a PR for review.

**Comment by chentschel** [comment]
@danfinlay Its not possible to use the npm with typescript. Can u please review the PR?

**Comment by danfinlay** [comment]
I merged the open PR, fixed one of the two reported issues. Published as `eth-sig-util@2.5.1`

**Comment by chentschel** [comment]
@danfinlay thanks for the merge. As for the 2nd issue @mrwillis , wouldn't it be solved using a ITypedValue[] , defining ITypedValue[] as array of string, or number ? 

```
export interface ITypedValue {
  [key: string]: string | number | ITypedValue | ITypedValue[]
}
```

**Comment by lazaridiscom** [comment]
I'm running too into ts related problems with eth-sig-util, too.

@danfinlay , possibly the index.d.ts file should be dropped for now (see some notes re "I" prefix https://github.com/MetaMask/KeyringController/pull/36#issuecomment-557933069), and the migration to TS should start in lower level packages (see https://github.com/MetaMask/eth-simple-keyring/issues/36). 

@chentschel, if "should also allow for string[] and number[]" is true, then personally I would expect to see those in the declaration file.

**Comment by danfinlay** [comment]
I'm willing to merge a PR either removing `index.d.ts` or improving it.

**Comment by lazaridiscom** [comment]
see #68

**Comment by lazaridiscom** [comment]
(related: MetaMask/metamask-extension#7601)

It looks like `eth-sig-util` should go on top of the migration list.

**Comment by lazaridiscom** [comment]
After looking at this a little bit, my suggestion here is (clearly) to remove the typedefs for now, before they get further adopted.

**Comment by danfinlay** [comment]
Fine. Pending a proper typescript conversion, since I haven't had time to make sure this is all working right, and things clearly aren't, I've removed typedefs in `eth-sig-util@2.5.2`.

I'm open to someone else doing the typescript conversion, and I may add a small gitcoin bounty to encourage it, and anyone else can too if the would value that feature.

**Comment by danfinlay** [comment]
Opened issue for actually converting to Typescript: https://github.com/MetaMask/eth-sig-util/issues/70

**Comment by lazaridiscom** [comment]
@danfinlay , please be aware that this (a full conversion) is neither a "Beginner Task", nor does it take "hours" (as you've filed on the bounty). @developerfred seems to want to give it a shot though, which is fine.

Just remember what happened in the past, when tasks which needed planning & research went out into smaller bounties.

Now, I've solved locally the last barrier I had, the preliminary ts-migration-process I extracted seems to work fine for this package, and the typedefs seem to be generated fine, too. Additional tasks spawn out, as usual (this is because of the very central nature of this package).

I could have a PR in 1 day, production-quality in 2 days (and this only because of the pre-work i've don in the last week), but naturally, I cannot justify to do this in context of tiny bounties, and my main interest is anyways  to fulfill MetaMask/metamask-extension#7601 (simply because this is urgently needed).

So, should you want to "go nuclear" on the overall mm organization (re typescript), just let me know - you know where to find me.

.

**Comment by lazaridiscom** [comment]
( one more thing: Note that I'm now (after insisting for it for several days) able to generate a  typdef file from *.js files (several bugs prevent this in normal setups), allowing for an even smoother (overall) migration to ts. )

This issue should be closable now, as its obsolete (no typedef file included in latest version).

Follow-up: #70
